services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 30s

  users-service:
    build: ./application
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./application/.env
    volumes:
      - ./application:/usr/src/app:delegated
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "nc", "-z", "rabbitmq", "5672"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  rabbitmq-data:
